Dev
SYSU-ECNC/net-toolbox-frontend pull request #2
Opened 2022-03-19 15:54 UTC by senkiii

2022-03-20 06:50 UTC, robinWongM requested changes
Review 完成，请看下评论

2022-03-20 06:50 UTC, robinWongM commented on net-toolbox/workspace.code-workspace
> +{
这个文件应该是不被提交到 Git 仓库的

2022-03-20 06:50 UTC, robinWongM commented on src/App.vue
> +        onclick='window.location.href="#/ping"'
1. 用 vue-router 实现跳转吧
2. 一般用 Vue 提供的绑定事件指令 `v-on`，简写 `@`：https://v3.cn.vuejs.org/guide/events.html ；不用这种直接在标签上写 onclick 的

2022-03-20 06:50 UTC, robinWongM commented on src/App.vue
> +        id="ping"
这里的 id 用处是什么呢

2022-03-20 06:50 UTC, robinWongM commented on src/components/AgentManagement.vue
> +
比较奇怪的空行

2022-03-20 06:50 UTC, robinWongM commented on src/components/DefaultPage.vue
> +  <div id="blank"></div>
这个只是为了用来撑大高度的么？可以用其他元素的 margin 来实现吧

2022-03-20 06:50 UTC, robinWongM commented on src/components/FetchUserName.vue
> +  reDirect() {
`redirect`

2022-03-20 06:50 UTC, robinWongM commented on src/components/HelloUser.vue
> +
空行

2022-03-20 06:50 UTC, robinWongM commented on src/components/HelloUser.vue
> +      //不知道写啥，应该是从fetchusername组件获得username，总之先占个位置在这里
其实没看明白那个组件的作用

2022-03-20 06:50 UTC, robinWongM commented on src/components/NotFound.vue
> +    <div id="blank"></div>
同上

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +  <div id="pingform">
命名规范：
1. HTML 中不区分大小写，所以 tag 名、属性名都用 kebab-case，id 和 class 的值也用纯小写，但是用 `-` 或者 `_` 来分割单词
2. JS 中用 camelCase，不用 - 和 _

```suggestion
  <div id="ping-form">
```

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +      v-model:value="chosenvalue"
```suggestion
      v-model:value="chosenValue"
```

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +      v-model:value="to_ping"
```suggestion
      v-model:value="toPing"
```

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +    <n-button type="info" @click="GoPing" id="go-ping">Go!</n-button>
```suggestion
    <n-button type="info" @click="goPing" id="go-ping">Go!</n-button>
```

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +    GoPing() {
```suggestion
    goPing() {
```

2022-03-20 06:50 UTC, robinWongM commented on src/components/PingForm.vue
> +#pingform {
```suggestion
#ping-form {
```

2022-03-20 06:50 UTC, robinWongM commented on src/main.ts
> +
空行

2022-03-20 06:50 UTC, robinWongM commented on vue.config.js
> +
空行

2022-03-20 06:53 UTC, robinWongM commented
之后开 Pull Request 的时候，标题和详情简要说一下变动的内容吧，自动生成的这个 `Dev` 就。。。没啥用

2022-03-20 07:44 UTC, senkiii commented on src/components/HelloUser.vue
> +      //不知道写啥，应该是从fetchusername组件获得username，总之先占个位置在这里
其实我也没写明白，这个版本我们先当无事发生过。。

2022-03-20 07:48 UTC, senkiii commented on src/App.vue
> +        id="ping"
写css用

2022-03-20 07:55 UTC, senkiii commented on src/App.vue
> +        onclick='window.location.href="#/ping"'
用router-link的话好像就没法使用组件库？🤔等下再改这个

2022-03-20 11:04 UTC, robinWongM commented on src/App.vue
> +        onclick='window.location.href="#/ping"'
- https://www.naiveui.com/zh-CN/light/components/menu#select.vue
- 或者，https://router.vuejs.org/zh/guide/essentials/navigation.html

2022-03-20 11:06 UTC, robinWongM commented on .gitignore
> +net-toolbox/workspace.code-workspace
已经被 Git 跟踪过的文件需要 `git rm --cached` 才可以移除跟踪

2022-03-20 11:06 UTC, robinWongM approved these changes, later dismissed

2022-03-21 16:27 UTC, robinWongM commented on src/components/AgentManagement.vue
> +const agentColumns = createColumns();
其实这里为什么要搞成一个函数呢

2022-03-21 16:27 UTC, robinWongM commented on src/components/PingForm.vue
> +    isDone: 'true',
应该是 `true` 而不是 `'true'`

2022-03-21 16:27 UTC, robinWongM commented on src/components/PingForm.vue
> +  //之后从后端获取JSON，在这里加一句JSON.parse……话说在JSON里写'true'的话，转换过来应该也还是字符串吧？
JSON 本身是可以表达布尔值的，而不是用字符串去套起来，所以应该直接拿到 `true` 和 `false`

2022-03-21 16:27 UTC, robinWongM commented on src/components/PingForm.vue
> +  }
一般不推荐把获取到的数据进行二次修改（immutable）。如果是为了让这个 `true` 和 `false` 在页面上以别的文字来显示，可以将这个转换逻辑写在 template 里（比如 `{{ isDone ? '已完成' : '进行中' }}`），或者用 computed/method 动态转换。

2022-03-23 14:56 UTC, robinWongM commented on src/components/PingForm.vue
> +      }"
或许这样就可以了？
```suggestion
      :row-key="(tableData: any) => tableData.time"
```

> 虽然我觉得 key 应当是 id 之类的，而不是时间
> 尽量别用 `any`

2022-05-05 12:25 UTC, closed without merging